### PR TITLE
Make cargo-miri run documentation tests

### LINKED ISSUE #584: `cargo miri test` does not run doc-tests
I am not sure what it would take to also make it build and execute doc-tests.  Probably just some tweaks in how we wrap `cargo rustc`?

### PR DESCRIPTION
**Pull request by teryror**
This would resolve #584.

It Works On My Machine. Specifically, it needs a version of rustdoc with [this change](https://github.com/rust-lang/rust/pull/80924), which was only merged yesterday, i.e. it needs the most recent nightly build. With that, I can run the entire [coca](https://github.com/teryror/coca) test suite successfully, which is what I used for testing this feature. Verbose output and/or purposefully changing a doc-test to fail confirm this is working as intended, and not just reported incorrectly.

However, updating `rustc-version` breaks several tests from Miri's own test suite, so merging this will have to wait. Still, I'm sure this would benefit a lot from code review and testing on other projects, in other build environments.

### CODE REVIEW

**Comment by teryror** [comment]
I had completely forgotten about `test-cargo-miri` since I'd been testing on my own project the whole time. This fixes an oversight of mine in `phase_cargo_runner`, and updates the tests to expect working doc-tests.

Given this still requires a newer rustdoc, I don't expect this to pass CI though.

File: test-cargo-miri/run-test.py [hunk 1]
```diff
@@ -21,6 +21,9 @@ def cargo_miri(cmd):
         args += ["--target", os.environ['MIRI_TEST_TARGET']]
     return args
 
+def scrub_timing_info(str):
+    return re.sub("finished in \d+\.\d\ds", "", str)
+
```
Comment (teryror) [inline test-cargo-miri/run-test.py:26]: This is a bit awkward, but I don't think I can stop rustdoc from emitting timing information, so this is the only way to stop fickle test failures.

**Comment by RalfJung** [comment]
Thanks a lot for this PR! I have this in my queue of things to do. Unfortunately, I am pretty busy currently and reviewing these PRs is but one of many things competing for my spare time, so it might take a week or more until I get around to taking a closer look at this. Sorry for that.

**Comment by teryror** [comment]
No worries, take all the time you need!

**Comment by RalfJung** [comment]
Has the rustdoc change landed in the rustc repository in the mean time? Can you rebase this PR over Miri master? That should now work with latest rustc.

File: test-cargo-miri/run-test.py (hunk 1 above)
Comment (RalfJung) [reply test-cargo-miri/run-test.py:26]: That seems fair, but the usual approach we take for variable output like this is slightly different: I suggest you make a `normalize_stdout` function which replaces the timing info by something like `finished in $TIME`, and you apply that *only to the process output*. The reference file is expected to contain the already-normalized output.

File: test-cargo-miri/test.stderr-rustdoc.ref [hunk 2]
```diff
@@ -1 +0,0 @@
-Running doctests is not currently supported by Miri.
```
Comment (RalfJung) [inline test-cargo-miri/test.stderr-rustdoc.ref:1]: Please entirely remove this file, it should not be needed any more.

File: cargo-miri/bin.rs [hunk 3]
```diff
@@ -585,6 +614,34 @@ fn phase_cargo_rustc(args: env::Args) {
         // (Need to do this here as cargo moves that "binary" to a different place before running it.)
         info.store(&out_filename("", ".exe"));
 
+        // Rustdoc expects us to exit with an error code if the test is marked as `compile_fail`,
+        // so we need to run Miri with `MIRI_BE_RUSTC` for a check-only build.
```
Comment (RalfJung) [inline cargo-miri/bin.rs:618]: I don't understand the command here. What do the error code and `MIRI_BE_RUSTC` have to to with each other?

File: cargo-miri/bin.rs [hunk 4]
```diff
@@ -729,6 +786,57 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+
+fn phase_cargo_rustdoc(fst_arg: &str, mut args: env::Args) {
+    let verbose = std::env::var_os("MIRI_VERBOSE").is_some();
+
+    // phase_cargo_miri sets the RUSTDOC env var to ourselves, so we can't use that here;
+    // just default to a straight-forward invocation for now:
+    let mut cmd = Command::new(OsString::from("rustdoc"));
+
+    let extern_flag = "--extern";
+    assert!(fst_arg != extern_flag);
```
Comment (RalfJung) [inline cargo-miri/bin.rs:805]: Please add a comment explaining why this assertion is important.

File: cargo-miri/bin.rs [hunk 5]
```diff
@@ -729,6 +786,57 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+
+    // Patch --extern arguments to use *.rmeta files, since phase_cargo_rustc only creates stub *.rlib files.
+    while let Some(arg) = args.next() {
+        if arg == extern_flag {
+            cmd.arg(extern_flag); // always forward flag, but adjust filename
+            // `--extern` is always passed as a separate argument by cargo.
+            let next_arg = args.next().expect("`--extern` should be followed by a filename");
+            if let Some(next_lib) = next_arg.strip_suffix(".rlib") {
+                // If this is an rlib, make it an rmeta.
+                cmd.arg(format!("{}.rmeta", next_lib));
```
Comment (RalfJung) [inline cargo-miri/bin.rs:816]: This same code also exists in `phase_cargo_runner`, right? Is there some way to avoid the code duplication?

File: cargo-miri/bin.rs [hunk 6]
```diff
@@ -729,6 +786,57 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+            } else {
+                // Some other extern file (e.g., a `.so`). Forward unchanged.
+                cmd.arg(next_arg);
+            }
+        } else {
+            cmd.arg(arg);
+        }
+    }
+
+    cmd.arg("-Z").arg("unstable-options");
```
Comment (RalfJung) [inline cargo-miri/bin.rs:826]: Presumably this is needed for `--test-builder`/`--runtool`? Please add a comment along those lines.

File: cargo-miri/bin.rs [hunk 7]
```diff
@@ -729,6 +786,57 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+    
+    let cargo_miri_path = std::env::current_exe().expect("current executable path invalid");
+    cmd.arg("--test-builder").arg(&cargo_miri_path);
+    cmd.arg("--runtool").arg(&cargo_miri_path);
```
Comment (RalfJung) [inline cargo-miri/bin.rs:830]: I assume this will enter the `phase_cargo_rustc` and `phase_cargo_runner` code paths, respectively?

Comment (RalfJung) [reply cargo-miri/bin.rs:830]: Ah, that relies on the `invoked_as_rustc_from_rustdoc` check. Please add a comment explaining that connection.

File: cargo-miri/bin.rs [hunk 8]
```diff
@@ -745,6 +853,30 @@ fn main() {
...
+        // The runner is invoked as `$runtool ($runtool-arg)* output_file;
+        // since we don't specify any runtool-args, and rustdoc supplies multiple arguments to
+        // the test-builder unconditionally, we can just check the number of remaining arguments:
+        if args.len() == 1 {
+            let arg = args.next().unwrap();
+            let binary = Path::new(&arg);
+            if binary.exists() {
+                phase_cargo_runner(binary, args);
+            } else {
+                show_error(format!("`cargo-miri` called with non-existing path argument `{}`; please invoke this binary through `cargo miri`", arg));
```
Comment (RalfJung) [inline cargo-miri/bin.rs:871]:
```suggestion
                show_error(format!("`cargo-miri` called with non-existing path argument `{}` in rustdoc mode; please invoke this binary through `cargo miri`", arg));
```

File: cargo-miri/bin.rs (hunk 3 above)
Comment (RalfJung) [reply cargo-miri/bin.rs:618]: Oh I think I get it... so the point is that we'd *want* to just write the JSON file and be done, but actually we cannot since that would always succeed but we need to detect syntax errors. Can you extend the comment a bit?
```suggestion
        // so just creating the JSON is not enough: we need to detect syntax errors, so we
        // run Miri with `MIRI_BE_RUSTC` for a check-only build.
```

File: cargo-miri/bin.rs [hunk 9]
```diff
@@ -585,6 +614,34 @@ fn phase_cargo_rustc(args: env::Args) {
...
+            let mut cmd = miri();
+
+            // use our own sysroot
+            if !has_arg_flag("--sysroot") {
+                let sysroot = env::var_os("MIRI_SYSROOT")
+                    .expect("the wrapper should have set MIRI_SYSROOT");
+                cmd.arg("--sysroot").arg(sysroot);
+            }
+            
+            // don't go into "code generation" (i.e. validation)
```
Comment (RalfJung) [inline cargo-miri/bin.rs:629]: What do you mean by "calidation"? `MIRI_BE_RUSTC` would actually do proper code generation.

File: cargo-miri/bin.rs [hunk 10]
```diff
@@ -585,6 +614,34 @@ fn phase_cargo_rustc(args: env::Args) {
...
+            if info.args.iter().position(|arg| arg.starts_with("--emit=")).is_none() {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:630]: Can't we use one of the arg-parsing helper functions for this?

Comment (RalfJung) [reply cargo-miri/bin.rs:630]: Also, will this ever be `some`? Might be worth asserting this, since what we certainly do not want is for this to produce a binary that overwrites the JSON file...

File: cargo-miri/bin.rs [hunk 11]
```diff
@@ -585,6 +614,34 @@ fn phase_cargo_rustc(args: env::Args) {
         // (Need to do this here as cargo moves that "binary" to a different place before running it.)
         info.store(&out_filename("", ".exe"));
 
+        // Rustdoc expects us to exit with an error code if the test is marked as `compile_fail`,
+        // so we need to run Miri with `MIRI_BE_RUSTC` for a check-only build.
+        if std::env::var_os("MIRI_CALLED_FROM_RUSTDOC").is_some() {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:619]: Please document this env var in the README, near `MIRI_BE_RUSTC`.

File: cargo-miri/bin.rs (hunk 10 above)
Comment (teryror) [reply cargo-miri/bin.rs]: As of right now, rustdoc only ever passes `--emit=metadata`, but I did add an assert there.

The arg-parsing helpers aren't applicable here, because they look for exact matches, rather than a prefix.

File: cargo-miri/bin.rs (hunk 9 above)
Comment (teryror) [reply cargo-miri/bin.rs]: I was under the impression that that's what the `--emit` argument effectively does here. I adjusted the comment to communicate this more clearly.

**Comment by teryror** [comment]
> Has the rustdoc change landed in the rustc repository in the mean time? Can you rebase this PR over Miri master? That should now work with latest rustc.

This has been merged for about a week now, yes.

I rolled up all of your suggestions into a single commit, then rebased and force-pushed, we should be good to go. Let's see what CI has to say about it.

File: cargo-miri/bin.rs (hunk 10 above)
Comment (RalfJung) [reply cargo-miri/bin.rs]: Checking the `--emit` flag with the helpers should work though -- the helpers *do* support `=`.

**Comment by RalfJung** [comment]
> I rolled up all of your suggestions into a single commit, then rebased and force-pushed, we should be good to go.

I'd prefer if you could avoid squashing while we are still doing review. That makes my job much easier as it means I do not have to re-read all your code. :)

> Let's see what CI has to say about it.

Is the version in `rust-version` new enough to contain that fix?

**Comment by teryror** [comment]
Argh, sorry about that. Good thing this was mostly about adding more comments.

The `rust_version` is new enough, the CI check fails because doc-tests aren't run for all targets, so we'd need a different `test.default.stdout.ref` depending on the platform, it would seem. I find that a bit strange, wouldn't it be better to enable that somehow? I'm not quite sure _how_, though. What's your preference here?

File: cargo-miri/bin.rs [hunk 12]
```diff
@@ -646,6 +708,18 @@ fn phase_cargo_rustc(args: env::Args) {
     }
 }
 
+fn try_forward_patched_extern_arg(args: &mut impl Iterator<Item = String>, cmd: &mut Command) {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:711]: Why "try"?

File: cargo-miri/bin.rs (hunk 9 above)
Comment (RalfJung) [reply cargo-miri/bin.rs]: "validation" is rather ambiguous about what is being validated; that's why my question was about. The new comment explains that, thanks!

File: README.md [hunk 13]
```diff
@@ -282,6 +282,10 @@ different Miri binaries, and as such worth documenting:
   that the compiled `rlib`s are compatible with Miri.
   When set while running `cargo-miri`, it indicates that we are part of a sysroot
   build (for which some crates need special treatment).
+* `MIRI_CALLED_FROM_RUSTDOC` when set to any value tells `cargo-miri` that it is
+  running as a child process of `rustdoc`, which invokes it twice for each doc-test
+  and requires special treatment, most notably a check-only build before validation.
```
Comment (RalfJung) [inline README.md:287]: Here "validation" is again; could you replace this by something more specific? I don't know what validation you mean here.

"interpretation" or "running the interpreter" would work, I think.

File: cargo-miri/bin.rs (hunk 10 above)
Comment (RalfJung) [reply cargo-miri/bin.rs]: Oh the problem is that you are working on `info.args`, not the args of the current process,,, makes sense. But a brief comment along those lines would be a good idea I think.

**Comment by RalfJung** [comment]
> The rust_version is new enough, the CI check fails because doc-tests aren't run for all targets, so we'd need a different test.default.stdout.ref depending on the platform, it would seem. I find that a bit strange, wouldn't it be better to enable that somehow? I'm not quite sure how, though. What's your preference here?

Looks like cargo by default does not run doctests in cross-mode, but an experimental feature exists to fix that: https://github.com/rust-lang/cargo/issues/7040. Maybe our test suite could use that?

File: cargo-miri/bin.rs (hunk 10 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs]: > working on `info.args`, not the args of the current process,,,

Would [`ArgFlagValueIter`](https://github.com/rust-lang/miri/blob/853254f467e26ee1d5d46b7079c96c4f53f072a1/cargo-miri/bin.rs#L102-L103) from #1675 help? That accepts any iterator (of type `TakeWhile<env::Args, fn(&String) -> bool>` currently

<details>
<summary>but can be changed to a generic type)</summary>

```diff
--- a/cargo-miri/bin.rs
+++ b/cargo-miri/bin.rs
@@ -100,12 +100,12 @@ fn has_arg_flag(name: &str) -> bool {
 }
 
 /// Yields all values of command line flag `name`.
-struct ArgFlagValueIter<'a> {
-    args: TakeWhile<env::Args, fn(&String) -> bool>,
+struct ArgFlagValueIter<'a, I> {
+    args: I,
     name: &'a str,
 }
 
-impl<'a> ArgFlagValueIter<'a> {
+impl<'a> ArgFlagValueIter<'a, TakeWhile<env::Args, fn(&String) -> bool>> {
     fn new(name: &'a str) -> Self {
         Self {
             // Stop searching at `--`.
@@ -115,7 +115,7 @@ impl<'a> ArgFlagValueIter<'a> {
     }
 }
 
-impl Iterator for ArgFlagValueIter<'_> {
+impl<I: Iterator<Item = String>> Iterator for ArgFlagValueIter<'_, I> {
     type Item = String;
 
     fn next(&mut self) -> Option<Self::Item> {
```
</details>

Comment (RalfJung) [reply cargo-miri/bin.rs]: Yeah, we'd have to generalize, but then this should work. We should also generalize `ArgFlagValueIter::new` then.

File: cargo-miri/bin.rs (hunk 12 above)
Comment (teryror) [reply cargo-miri/bin.rs:711]: Because it can panic on a malformed `--extern` argument, was my reasoning.

**Comment by teryror** [comment]
That should do it, I think. I'll get around to merging this with #1675 later today, maybe tomorrow.

File: cargo-miri/bin.rs (hunk 12 above)
Comment (RalfJung) [reply cargo-miri/bin.rs:711]: `try` usually indicates an `Option` or `Result` return type... so I think it'd be better to remove it here.

Comment (teryror) [reply cargo-miri/bin.rs]: Done.

**Comment by RalfJung** [comment]
Not supporting cross-running of doctests at first is also fine, if it turns out to be hard (and it seems like it does^^).

You can use the existing [`is_foreign`](https://github.com/rust-lang/miri/blob/e23e0b2d12af068eb9324cd4bbefdfdd042eb19e/test-cargo-miri/run-test.py#L73) variable to swap out the ref file. But it would be good if we didn't have to do this for *each* test. Maybe pass `--no-doc` for most of them or so?

**Comment by teryror** [comment]
Sounds good to me. I should be able to finish up by tomorrow in that case :)

If no one else picks this up, I should be able to set some time aside to investigate cross-running starting around mid-March (I have exams coming up until then).

**Comment by RalfJung** [comment]
> If no one else picks this up, I should be able to set some time aside to investigate cross-running starting around mid-March (I have exams coming up until then).

Awesome. :) Once this lands, it's probably best to create an issue and leave such notes there. And good call on not letting Miri distract you too much from your exams :+1:

**Comment by RalfJung** [comment]
@teryror I'm sorry I lost track... is this PR waiting for me to review it, or do you have further changes planned?

**Comment by teryror** [comment]
This is ready for review, yes, probably should have pinged you about that, sorry. I didn't rebase in a week or so, no changes planned besides that.

File: cargo-miri/bin.rs [hunk 14]
```diff
@@ -63,7 +65,13 @@ impl CrateRunInfo {
         let args = args.collect();
         let env = env::vars_os().collect();
         let current_dir = env::current_dir().unwrap().into_os_string();
-        Self::RunWith(CrateRunEnv { args, env, current_dir })
+
+        let mut stdin = Vec::new();
+        if env::var_os("MIRI_CALLED_FROM_RUSTDOC").is_some() {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:70]: In the interest of keeping the logic in one place, I think it would be better to pass in a `capture_stdin: bool`, and do the env var check on the caller side.

File: cargo-miri/bin.rs [hunk 15]
```diff
@@ -627,15 +656,55 @@ fn phase_cargo_rustc(args: env::Args) {
...
+            } else {
+                return;
+            };
+
+            // use our own sysroot
+            if !has_arg_flag("--sysroot") {
+                let sysroot = env::var_os("MIRI_SYSROOT")
+                    .expect("the wrapper should have set MIRI_SYSROOT");
+                cmd.arg("--sysroot").arg(sysroot);
+            }
```
Comment (RalfJung) [inline cargo-miri/bin.rs:678]: This is code duplication with the "Use our custom sysroot" below, right? But the logic is slightly different. Why that?

File: cargo-miri/bin.rs [hunk 16]
```diff
@@ -793,6 +865,73 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+        exec(cmd)
+    }
+}
+
+fn phase_cargo_rustdoc(fst_arg: &str, mut args: env::Args) {
+    let verbose = std::env::var_os("MIRI_VERBOSE").is_some();
+
+    // phase_cargo_miri sets the RUSTDOC env var to ourselves, so we can't use that here;
+    // just default to a straight-forward invocation for now:
+    let mut cmd = Command::new(OsString::from("rustdoc"));
```
Comment (RalfJung) [inline cargo-miri/bin.rs:881]:
```suggestion
    let mut cmd = Command::new("rustdoc");
```
At least I think that should work, based on the docs.

File: cargo-miri/bin.rs [hunk 17]
```diff
@@ -793,6 +865,73 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+    // Because of the way the main function is structured, we have to take the first argument spearately
+    // from the rest; to simplify the following argument patching loop, we'll just skip that one.
+    // This is fine for now, because cargo will never pass --extern arguments in the first position,
+    // but we should defensively assert that this will work.
+    let extern_flag = "--extern";
+    assert!(fst_arg != extern_flag);
+    cmd.arg(fst_arg);
+    
+    let runtool_flag = "--runtool";
+    let mut crossmode = fst_arg == runtool_flag;
```
Comment (RalfJung) [inline cargo-miri/bin.rs:892]:
```suggestion
    // `crossmode` records if *any* argument matches `runtool_flag`; here we check the first one.
    let mut crossmode = fst_arg == runtool_flag;
```

File: cargo-miri/bin.rs [hunk 18]
```diff
@@ -809,6 +948,30 @@ fn main() {
         return;
     }
 
+    // The way rustdoc invokes rustc is indistuingishable from the way cargo invokes rustdoc
+    // by the arguments alone, and we can't take from the args iterator in this case.
```
Comment (RalfJung) [inline cargo-miri/bin.rs:952]: What do you mean by "we can't take from the args iterator"?

File: test-cargo-miri/run-test.py [hunk 19]
```diff
@@ -71,26 +75,27 @@ def test_cargo_miri_run():
...
     test("`cargo miri test` (no isolation)",
         cargo_miri("test"),
-        "test.default.stdout.ref", rustdoc_ref,
+        default_ref, "test.stderr-empty.ref",
         env={'MIRIFLAGS': "-Zmiri-disable-isolation"},
     )
     test("`cargo miri test` (raw-ptr tracking)",
         cargo_miri("test"),
-        "test.default.stdout.ref", rustdoc_ref,
+        default_ref, "test.stderr-empty.ref",
```
Comment (RalfJung) [inline test-cargo-miri/run-test.py:93]: Can you change one of these tests to also pass `--no-doc`, just to make sure that that actually has the intended effect?

**Comment by RalfJung** [comment]
This looks great, I just have some minor nits. :)

File: cargo-miri/bin.rs [hunk 20]
```diff
@@ -627,15 +656,55 @@ fn phase_cargo_rustc(args: env::Args) {
...
+            };
+
+            // use our own sysroot
+            if !has_arg_flag("--sysroot") {
+                let sysroot = env::var_os("MIRI_SYSROOT")
+                    .expect("the wrapper should have set MIRI_SYSROOT");
+                cmd.arg("--sysroot").arg(sysroot);
+            }
+            
+            // ensure --emit argument for a check-only build is present
```
Comment (RalfJung) [inline cargo-miri/bin.rs:680]:
```suggestion
            // ensure --emit argument for a check-only build is present.
            // We cannot use the usual helpers since we need to check specifically in `env.args`.
```

File: cargo-miri/bin.rs [hunk 21]
```diff
@@ -627,15 +656,55 @@ fn phase_cargo_rustc(args: env::Args) {
...
+
+        // Rustdoc expects us to exit with an error code if the test is marked as `compile_fail`,
+        // just creating the JSON file is not enough: we need to detect syntax errors,
+        // so we need to run Miri with `MIRI_BE_RUSTC` for a check-only build.
+        if std::env::var_os("MIRI_CALLED_FROM_RUSTDOC").is_some() {
+            let mut cmd = miri();
+            let env = if let CrateRunInfo::RunWith(env) = info {
+                env
+            } else {
+                return;
```
Comment (RalfJung) [inline cargo-miri/bin.rs:670]: Can this ever happen? If not, it might be better to make this `unreachable!()`, just to be sure.

**Comment by RalfJung** [comment]
I just noticed there is a reference to #584 in `phase_cargo_miri`; that also needs to be updated.

**Comment by hyd-dev** [comment]
This PR does not pass a [test](https://github.com/rust-lang/miri/blob/0737de86f760a35408088f19c45c0617ffed21d0/test-cargo-miri/src/lib.rs#L6) that will be introduced in #1709:
<details>

```
## Running `cargo miri` tests
A libstd for Miri is now available in `/home/user/.cache/miri/HOST`.
Testing `cargo miri run` (no isolation)...
Testing `cargo miri run` (with arguments and target)...
Testing `cargo miri run` (subcrate, no ioslation)...
Testing `cargo miri test`...
--- BEGIN stdout ---

running 1 test
.
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out


running 7 tests
..i....
test result: ok. 6 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out

--- END stdout ---
--- BEGIN stderr ---
error[E0460]: found possibly newer version of crate `std` which `issue_1691` depends on
 --> /home/user/miri/test-cargo-miri/src/lib.rs:6:5
  |
6 |     issue_1691::use_me()
  |     ^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: the following crate versions were found:
          crate `std`: /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f5658153d127ddd.rlib
          crate `std`: /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f5658153d127ddd.so
          crate `issue_1691`: /home/user/miri/test-cargo-miri/target/x86_64-unknown-linux-gnu/debug/deps/libissue_1691-30200c4d8cd6fa63.rmeta

error: aborting due to previous error

error: test failed, to rerun pass '--doc'
--- END stderr ---

TEST FAIL: exit code was 1
```
</details>

[This](https://github.com/rust-lang/miri/commit/289a7fdf2255833cbee8c7c6b78c23b4927d67f6) can fix it (feel free to cherry-pick it, but it duplicates some `--sysroot` code, so probably needs to be deduplicated before landing, also note that it contains some unrelated whitespace diff because my editor trimmed trailing whitespaces automatically).

**Comment by RalfJung** [comment]
@teryror I haven't heard from you in a while, so I assume you moved on to other things. Thanks a lot for this PR! I will take over and finish it so that it can hopefully land soon. :)

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/miri/pull/1757.
