### ISSUE TITLE
"cargo miri run" fails: cannot alloc memory for unsized type

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#675]
Our [nightly CI job](https://travis-ci.com/rust-lang/miri/jobs/190852778) failed in a surprising way:

```
thread 'rustc' panicked at 'cannot alloc memory for unsized type', src/librustc_mir/interpret/place.rs:942:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
   7: rustc_mir::interpret::place::<impl rustc_mir::interpret::eval_context::InterpretCx<M>>::allocate
   8: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpretCx<M>>::run
   9: miri::eval_main
  10: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  11: rustc_interface::passes::create_global_ctxt::{{closure}}
  12: rustc_interface::passes::BoxedGlobalCtxt::enter
  13: <miri::MiriCompilerCalls as rustc_driver::Callbacks>::after_analysis
  14: rustc_interface::interface::run_compiler_in_existing_thread_pool
  15: std::thread::local::LocalKey<T>::with
  16: scoped_tls::ScopedKey<T>::set
  17: syntax::with_globals
query stack during panic:
end of query stack
```

That is with rust-lang/rust@b025802a2. CI on the last PR worked fine. Hence the offending commit is in https://github.com/rust-lang/rust/compare/f717b58dd70829f105960a071c7992b440720482...b025802a2.

**Comment by RalfJung** [comment]
The end of the trace is
```
 INFO 2019-04-06T09:13:01Z: rustc_mir::interpret::eval_context: PAUSING(7) std::sys_common::at_exit_imp::cleanup
 INFO 2019-04-06T09:13:01Z: rustc_mir::interpret::eval_context: ENTERING(8) <std::boxed::Box<dyn std::boxed::FnBox<(), Output = ()>> as std::ops::FnOnce<()>>::call_once
 INFO 2019-04-06T09:13:01Z: rustc_mir::interpret::step: // bb0
 INFO 2019-04-06T09:13:01Z: rustc_mir::interpret::step: Retag([fn entry] _1)
 INFO 2019-04-06T09:13:01Z: rustc_mir::interpret::step: Retag([fn entry] _2)
 INFO 2019-04-06T09:13:01Z: rustc_mir::interpret::step: StorageLive(_3)
```
so this is likely caused by https://github.com/rust-lang/rust/pull/59500.

**Comment by RalfJung** [comment]
Actually, Miri toolstate should currently be red, some of the run-pass tests ICE. However, due to https://github.com/laumann/compiletest-rs/issues/169, that does not make the test suite fail.

**Comment by RalfJung** [comment]
Uh... @eddyb I think I need your help. I am trying to implement unsized locals in Miri, and some weird stuff is happening. Namely, with the following example program
```rust
fn boxed(f: Box<dyn FnOnce() -> i32>) -> i32 {
    f()
}
boxed(Box::new({let x = 13; move || x}))
```
I am seeing this line of MIR
```
_0 = const std::ops::FnOnce::call_once(move _3, move _4) -> [return: bb2, unwind: bb4]
```
where `_3: dyn std::ops::FnOnce() -> i32`. How does that make any sense?!? Why can we call a trait object method on a non-pointer type?

**Comment by bjorn3** [comment]
> Why can we call a trait object method on a non-pointer type?

Because of https://github.com/rust-lang/rust/pull/54183 ("Implement by-value object safety")

**Comment by RalfJung** [comment]
I guess that makes sense. Miri doesn't support this nor custom self types.

This will be "fun"...

**Comment by RalfJung** [comment]
That was a good pointer, now at least the caller side works.

However, while the PR you mentioned said something about a shim that should be called, currently it calls the receiver method directly and that does not work very well...
```
error[E0080]: constant evaluation error: tried to call a function with argument of type [closure@tests/run-pass/closures.rs:52:44: 52:53 x:i32] passing data of type *mut dyn std::ops::FnOnce() -> i32
   --> /home/r/src/rust/rustc.2/src/liballoc/boxed.rs:702:9
    |
702 |         <F as FnOnce<A>>::call_once(*self, args)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tried to call a function with argument of type [closure@tests/run-pass/closures.rs:52:44: 52:53 x:i32] passing data of type *mut dyn std::ops::FnOnce() -> i32
    |
note: inside call to `<std::boxed::Box<dyn std::ops::FnOnce() -> i32> as std::ops::FnOnce<()>>::call_once` at tests/run-pass/closures.rs:44:5
   --> tests/run-pass/closures.rs:44:5
    |
44  |     f()
    |     ^^^
```

**Comment by RalfJung** [comment]
All right, the PR is up at https://github.com/rust-lang/rust/pull/59780 :)

**Comment by RalfJung** [comment]
Fixed by https://github.com/rust-lang/rust/pull/59780
