### ISSUE TITLE
Can't compile miri on windows

### ISSUE THREAD

**Issue by Stargateur** [rust-lang/miri#838]
I tried to compile miri on windows don't know if it related but I get a lot unresolved imports:

```none
error[E0432]: unresolved imports `crate::InterpCx`, `crate::FnVal`
  --> src\eval.rs:13:32
   |
13 |     InterpResult, InterpError, InterpCx, StackPopCleanup, struct_error,
   |                                ^^^^^^^^ no `InterpCx` in the root
14 |     Scalar, Tag, Pointer, FnVal,
   |                           ^^^^^ no `FnVal` in the root

error[E0433]: failed to resolve: use of undeclared type or module `FnVal`
   --> src\shims\foreign_items.rs:326:65
    |
326 |                     let ptr = this.memory_mut().create_fn_alloc(FnVal::Other(dlsym));
    |                                                                 ^^^^^ use of undeclared type or module `FnVal`

error[E0437]: type `ExtraFnVal` is not a member of trait `Machine`
   --> src\machine.rs:139:5
    |
139 |     type ExtraFnVal = Dlsym;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `Machine`

error[E0407]: method `call_extra_fn` is not a member of trait `Machine`
   --> src\machine.rs:162:5
    |
162 | /     fn call_extra_fn(
163 | |         ecx: &mut InterpCx<'mir, 'tcx, Self>,
164 | |         fn_val: Dlsym,
165 | |         args: &[OpTy<'tcx, Tag>],
...   |
169 | |         ecx.call_dlsym(fn_val, args, dest, ret)
170 | |     }
    | |_____^ not a member of trait `Machine`

error[E0412]: cannot find type `InterpCx` in this scope
   --> src\machine.rs:113:40
    |
113 | pub type MiriEvalContext<'mir, 'tcx> = InterpCx<'mir, 'tcx, Evaluator<'tcx>>;
    |                                        ^^^^^^^^ not found in this scope

error[E0412]: cannot find type `InterpCx` in this scope
   --> src\machine.rs:146:31
    |
146 |     fn enforce_validity(ecx: &InterpCx<'mir, 'tcx, Self>) -> bool {
    |                               ^^^^^^^^ not found in this scope

error[E0412]: cannot find type `InterpCx` in this scope
   --> src\machine.rs:152:19
    |
152 |         ecx: &mut InterpCx<'mir, 'tcx, Self>,
    |                   ^^^^^^^^ not found in this scope

error[E0412]: cannot find type `InterpCx` in this scope
   --> src\machine.rs:163:19
    |
163 |         ecx: &mut InterpCx<'mir, 'tcx, Self>,
    |                   ^^^^^^^^ not found in this scope

error[E0412]: cannot find type `InterpCx` in module `rustc_mir::interpret`
   --> src\machine.rs:174:41
    |
174 |         ecx: &mut rustc_mir::interpret::InterpCx<'mir, 'tcx, Self>,
    |                                         ^^^^^^^^ not found in `rustc_mir::interpret`
```
etc... is this expected on windows ?

I did a fresh clone and:

```bash
$ git checkout 365548007804d711b997941d634ecebf7fc03414
$ rustup override set nightly
$ rustc --version
rustc 1.37.0-nightly (0af8e872e 2019-06-30)
$ cargo build
```

I have also try `./miri build`

**Comment by RalfJung** [comment]
No this is not about windows, you are using the wrong version of rustc.

At the moment I am writing this, Miri master needs the latest nightly. Yours is more than two weeks out of date.

**Comment by Stargateur** [comment]
This indeed compile with `rustc 1.38.0-nightly (71f9384e3 2019-07-12)` I didn't expect this because I did an update recently (for me). Even clippy is not available for this nightly version on windows I have to remove it to be able to update.
